name: monitoring

services:
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=30d"
      - "--storage.tsdb.path=/prometheus"

  grafana:
    image: grafana/grafana:11.5.0
    container_name: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - prometheus
      - grafana
      - cadvisor
      - node-exporter

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.4
    container_name: nginx-exporter
    restart: always
    command:
      - "-nginx.scrape-uri=http://nginx/status"
    depends_on:
      - nginx

volumes:
  grafana_data:
  prometheus_data:
